csi_driver_nfs_version: v3.0.0
csi_driver_nfs_enabled: false
csi_driver_nfs_chart_download_url: "https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/latest/csi-driver-nfs-v3.0.0.tgz"

csi_driver_nfs_checksums:
  amd64:
    v3.0.0: 146a007cadd3cc95cc7c0eb4655bd3dc4cebd71453417190b31ff7fac521c426 # 如果和文件的sha256sum值不一致的话，会重新下载文件

csi_driver_nfs_checksum: "{{csi_driver_nfs_checksums[image_arch][csi_driver_nfs_version] }}"

nfs_node_driver_image_repo: k8s.gcr.io/sig-storage/csi-node-driver-registrar
nfs_node_driver_image_tag: v2.3.0

nfs_provisioner_image_repo: k8s.gcr.io/sig-storage/csi-provisioner
nfs_provisioner_image_tag: v2.1.0

nfs_liveness_image_repo: k8s.gcr.io/sig-storage/livenessprobe
nfs_liveness_image_tag: v2.3.0

nfs_csi_image_repo: mcr.microsoft.com/k8s/csi/nfs-csi
nfs_csi_image_tag: latest
