---
- block:
  - name: Krew | Install git offline on CentOS 7
    shell:
      cmd: yum install --disablerepo='*' -y *.rpm #el7
      chdir: /tmp/git/
    register: yum_result
    when:
      - ansible_pkg_mgr in ['yum']
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"
    ignore_errors: true

  - name: Krew | Install git offline on CentOS 8
    shell:
      cmd: yum install --disablerepo='*' --allowerasing -y *.rpm #el8
      chdir: /tmp/git/
    when:
      - ansible_pkg_mgr in ['yum']
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "8"

  - name: Krew | judge yum errors
    fail:
      msg: "yum install error"
    when: "'需要' in yum_result.stdout"

