- name: ChartMuseum | Clean
  include_tasks: clean.yml

- name: ChartMuseum | Download Chart
  include_tasks: "{{ playbook_dir }}/roles/download/tasks/download_chart.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.chartmuseum_chart) }}"

- name: ChartMuseum | Deploy ChartMuseum
  include_tasks: deploy.yml
  vars:
    chart_name: chartmuseum

