---
- hosts: localhost
  gather_facts: false
  tasks:
#    - name: Clean artifact path
#      file:
#        state: absent
#        path: /tmp/kubespray_cache
#    - name: Copy cached files
#      copy:
#        src: ../kubespray_cache
#        dest: /tmp/

- hosts: k8s-cluster
  gather_facts: false
  tasks:
    - name: Clean required_pkgs path
      file:
        state: absent
        path: /tmp/required_pkgs
    - name: Clean docker path
      file:
        state: absent
        path: /tmp/docker
    - name: Clean releases path
      file:
        state: absent
        path: /tmp/releases

    - name: Clean releases path
      file:
        state: absent
        path: /tmp/artifacts

#    - name: Remove docker binaries
#      yum:
#        name: docker-ce
#        state: absent
#        disablerepo: '*'
#
#    - name: Clean kubelet kubeadm
#      file:
#        path: /usr/local/bin/kubeadm
#        state: absent
#
#    - name: Clean kubelet kubeadm
#      file:
#        path: /usr/local/bin/kubelet
#        state: absent
