---
- hosts: localhost
  gather_facts: false
  connection: local # run locally
  vars:
    ssh_key_filename: "sshkey.pem"
  tasks:
    - name: SSHKEY | check .ssh local directory exists
      stat:
        path: "~/.ssh"
      register: ssh_directory_exists_check

    - name: SSHKEY | create ~/.ssh local directory
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
      register: ssh_directory_creation
      when: ssh_directory_exists_check is defined and ssh_directory_exists_check.stat.exists == false

    - name: SSHKEY | copy keyfile to local machine
      copy:
        content: "{{remote_sshkey}}"
        dest: "~/.ssh/{{ssh_key_filename}}"
        mode: "0600"

    - name: SSHKEY | check .ssh/config file exists
      stat:
        path: "~/.ssh/config"
      register: ssh_config_file_exists_check

    - debug:
        var: ssh_config_file_exists_check

    - name: SSHKEY | create the ~/.ssh/config file
      file:
        path: "~/.ssh/config"
        state: touch
        mode: "0644"
      register: ssh_config_file_creation
      when: ssh_config_file_exists_check is defined and ssh_config_file_exists_check.stat.exists == false

    - name: SSHKEY | add the new ssh key to the ~/.ssh/config file
      lineinfile:
        path: "~/.ssh/config"
        line: "IdentityFile ~/.ssh/{{ssh_key_filename}}"
        state: present
        backup: yes
      register: ssh_config_file_key_addition

    - debug:
        var: ssh_config_file_key_addition


